//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiAging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_RECETA
    {
        public int ID { get; set; }
        public string CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public int ID_RECETA { get; set; }
        public int ID_PACIENTE { get; set; }
        public int ID_EXAMEN { get; set; }
    
        public virtual EXAMENES EXAMENES { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual RECETA RECETA { get; set; }
    }
}
